### ISSUE TITLE
Poor performance (significant overhead) of the runner

### ISSUE THREAD

**Issue by quantverse** [getgauge/gauge-python#79] opened 2018-05-22 14:36 UTC
### Description
Hello,

we are looking for a good BDD runner for Python (an alternative to Behave to compare) and we like the way the specs are written in Gauge (in MarkDown). However, we don't like the performance of the runner. It seems it takes at least 150ms for a trivial step. For instance, if I take the reference example created by `gauge init python` and if we duplicate steps so there are 20 steps in total (see Steps to reproduce). These steps are really trivial, but it still takes about 3 seconds to run them all (150 ms each). There is probably some overhead in the runner, causing a small delay added while executing each step. In Behave, this takes something like 250 ms in total (all steps together). Unfortunately this is quite unusable for larger testing scenarios. Any chance to improve this? Or are we doing something wrong?

### Steps to reproduce
1. Initialize an example project by running `gauge init python`
2. Replace `example.spec` by https://gist.github.com/quantverse/03de98ab0141780421593408efcdbddb
3. Run `gauge run specs`

### Information that will help us debug

* Gauge version
```
Gauge version: 0.9.8
Commit Hash: c23df9f

Plugins
-------
html-report (4.0.4)
python (0.3.2)
screenshot (0.0.1)
```
* Gauge Python plugin version: **0.3.2**
* Python version: **3.6.5**
* `getgauge` package version, run `pip3 show getgauge` to get it
```
Name: getgauge
Version: 0.3.2
Summary: Enables Python support for Gauge
Home-page: https://github.com/getgauge/gauge-python
Author: Gauge Team
Author-email: getgauge@outlook.com
License: MIT
Location: /home/carloss/PycharmProjects/gauge-test/venv/lib/python3.6/site-packages
Requires: redBaron, ptvsd, grpcio, protobuf
```
* OS information: **Kubuntu 18.04 LTS amd64**

**Comment by BugDiver** [comment] 2018-05-23 10:53
@quantverse Thanks for reporting this issue.
I tried to follow your steps and reproduce the error.
Here are my findings -
* Updated the `example.spec` with the provided gist.
*  Console output of `gauge run specs`

```
➜  python-foo gauge run specs
Python: 3.6.1
# Specification Heading
  ## Vowel counts	 ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔

Successfully generated html-report to => /Users/bugdiver/projects/python-foo/reports/html-report/index.html
Specifications:	1 executed	1 passed	0 failed	0 skipped
Scenarios:	1 executed	1 passed	0 failed	0 skipped

Total time taken: 34ms
```

* I ran `guage run specs` with `time` command

```
➜  python-foo time gauge run specs
Python: 3.6.1
# Specification Heading
  ## Vowel counts	 ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔

Successfully generated html-report to => /Users/bugdiver/projects/python-foo/reports/html-report/index.html
Specifications:	1 executed	1 passed	0 failed	0 skipped
Scenarios:	1 executed	1 passed	0 failed	0 skipped

Total time taken: 34ms
gauge run specs  1.24s user 0.27s system 96% cpu 1.574 total
```

* Just to make sure I ran it with verbse flag,
```
➜  python-foo gauge run specs -v
Python: 3.6.5
# Specification Heading
  ## Vowel counts
      * The word "gauge" has "3" vowels.	 ...[PASS]
      * Almost all words have vowels

         |Word  |Vowel Count|
         |------|-----------|
         |Gauge |3          |
         |Mingle|2          |
         |Snap  |1          |
         |GoCD  |1          |
         |Rhythm|0          |	 ...[PASS]
      * The word "gauge" has "3" vowels.	 ...[PASS]
      * Almost all words have vowels

         |Word  |Vowel Count|
         |------|-----------|
         |Gauge |3          |
         |Mingle|2          |
         |Snap  |1          |
         |GoCD  |1          |
         |Rhythm|0          |	 ...[PASS]
      * The word "gauge" has "3" vowels.	 ...[PASS]
      * Almost all words have vowels

         |Word  |Vowel Count|
         |------|-----------|
         |Gauge |3          |
         |Mingle|2          |
         |Snap  |1          |
         |GoCD  |1          |
         |Rhythm|0          |	 ...[PASS]
      * The word "gauge" has "3" vowels.	 ...[PASS]
      * Almost all words have vowels

         |Word  |Vowel Count|
         |------|-----------|
         |Gauge |3          |
         |Mingle|2          |
         |Snap  |1          |
         |GoCD  |1          |
         |Rhythm|0          |	 ...[PASS]
      * The word "gauge" has "3" vowels.	 ...[PASS]
      * Almost all words have vowels

         |Word  |Vowel Count|
         |------|-----------|
         |Gauge |3          |
         |Mingle|2          |
         |Snap  |1          |
         |GoCD  |1          |
         |Rhythm|0          |	 ...[PASS]
      * The word "gauge" has "3" vowels.	 ...[PASS]
      * Almost all words have vowels

         |Word  |Vowel Count|
         |------|-----------|
         |Gauge |3          |
         |Mingle|2          |
         |Snap  |1          |
         |GoCD  |1          |
         |Rhythm|0          |	 ...[PASS]
      * The word "gauge" has "3" vowels.	 ...[PASS]
      * Almost all words have vowels

         |Word  |Vowel Count|
         |------|-----------|
         |Gauge |3          |
         |Mingle|2          |
         |Snap  |1          |
         |GoCD  |1          |
         |Rhythm|0          |	 ...[PASS]
      * The word "gauge" has "3" vowels.	 ...[PASS]
      * Almost all words have vowels

         |Word  |Vowel Count|
         |------|-----------|
         |Gauge |3          |
         |Mingle|2          |
         |Snap  |1          |
         |GoCD  |1          |
         |Rhythm|0          |	 ...[PASS]
      * The word "gauge" has "3" vowels.	 ...[PASS]
      * Almost all words have vowels

         |Word  |Vowel Count|
         |------|-----------|
         |Gauge |3          |
         |Mingle|2          |
         |Snap  |1          |
         |GoCD  |1          |
         |Rhythm|0          |	 ...[PASS]
      * The word "gauge" has "3" vowels.	 ...[PASS]
      * Almost all words have vowels

         |Word  |Vowel Count|
         |------|-----------|
         |Gauge |3          |
         |Mingle|2          |
         |Snap  |1          |
         |GoCD  |1          |
         |Rhythm|0          |	 ...[PASS]

Successfully generated html-report to => /Users/bugdiver/projects/python-foo/reports/html-report/index.html
Specifications:	1 executed	1 passed	0 failed	0 skipped
Scenarios:	1 executed	1 passed	0 failed	0 skipped

Total time taken: 41ms
```

### My Environment details
* **Gauge**
```
➜  python-foo gauge -v
Gauge version: 0.9.8
Commit Hash: c23df9f

Plugins
-------
html-report (4.0.4)
python (0.3.2)
screenshot (0.0.1)
```
* **Python**
```
Python 3.6.5

pip 10.0.1 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)

➜  python-foo pip3 show getgauge
Name: getgauge
Version: 0.3.2
Summary: Enables Python support for Gauge
Home-page: https://github.com/getgauge/gauge-python
Author: Gauge Team
Author-email: getgauge@outlook.com
License: MIT
Location: /Users/bugdiver/Library/Python/3.6/lib/python/site-packages
Requires: redBaron, grpcio, ptvsd, protobuf
Required-by:

```

* **OS**

```
MacOS High Sierra
Processor 2.8 GHz Intel Core i7
Memory 16 GB 1600 MHz DDR3
```

**Comment by sguptatw** [comment] 2018-05-28 10:13
**Test Case**
With execution of `gauge run` multiple times the time taken to execute must be relatively similar.

**Current behavior**
In Version
```
Gauge version: 0.9.9.nightly-2018-05-24
Commit Hash: 2150e31

Plugins
-------
python (0.3.3.nightly-2018-05-28)
```
The performance of execution is improved drastically.

However, running it multiple times increases the time taken to execute the specs incrementally.

**Steps to replicate**
* With the specification mentioned in the original issue, execute the specification consecutively a couple of times
> The time taken to execute the specs increase incrementally

**Comment by NivedhaSenthil** [comment] 2018-05-28 11:55
Running specs from vscode and linux docker container on mac seems to be fine. Execution time is average.

**Comment by sguptatw** [comment] 2018-05-28 12:04
The incremental increase in execution time(few milliseconds) happens for a couple of runs. After which the execution time is comparable to the original run. Hence closing the issue.

**Comment by sguptatw** [comment] 2018-05-28 12:04
Fix for the performance can be found in
```
Gauge version: 0.9.9.nightly-2018-05-24
Commit Hash: 2150e31

Plugins
-------
python (0.3.3.nightly-2018-05-28
```

**Closed by sguptatw** 2018-05-28 12:04 UTC
Labels: Linux, in progress, performance
